name: Update README.md
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run GitPortfolio
        uses: iosifache/gitportfolio@main
        with:
          config: ./config.yaml
          pat: ${{ secrets.pat }}
          datasources: ./custom_datasources
          template: ./TEMPLATE.md
          output: ./README.md
